/** Staff-only data is fetched with a memory-only bearer credential. No embedded event data. */
export const humanArtworkReviewPage = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Posy · Artwork review</title><style>
*{box-sizing:border-box}body{margin:0;background:#faf8f4;color:#243044;font:16px/1.5 system-ui,sans-serif}
header,main{max-width:1200px;margin:auto;padding:24px}header{border-bottom:1px solid #dedbd5}
h1{font:38px Georgia,serif;margin:8px 0}h2{font:26px Georgia,serif}p{max-width:72ch}
button,input,textarea{font:inherit;padding:10px;border:1px solid #b9b9b5;border-radius:8px}button{cursor:pointer;background:white;color:#243044}button.primary{background:#243044;color:white}button:disabled{opacity:.45;cursor:not-allowed}
button:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #9873c6;outline-offset:2px}
.bar{display:flex;gap:12px;flex-wrap:wrap;align-items:center}.layout{display:grid;grid-template-columns:260px 1fr;gap:24px;margin-top:24px}
#queue button{display:block;width:100%;text-align:left;margin:0 0 10px}article{min-width:0;background:white;border:1px solid #dedbd5;border-radius:14px;padding:24px}
pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.5 system-ui}.viewer{overflow:auto;max-height:85vh}#art{display:block;max-width:100%;width:356px;height:auto;margin:16px 0;border:1px solid #dedbd5}#art.full{width:auto;max-width:none}
#previous-art{display:block;max-width:100%;width:356px;height:auto;margin:16px 0}#previous-art.full{width:auto;max-width:none}
label.check{display:flex;gap:12px;margin:14px 0}input[type=checkbox]{width:20px;height:20px;flex-shrink:0}textarea{width:100%;min-height:90px}#status{min-height:24px;color:#654471}.muted{color:#596271;font-size:14px}[hidden]{display:none!important}
@media(max-width:700px){header,main{padding:16px}.layout{grid-template-columns:1fr}article{padding:16px}h1{font-size:30px}}
</style></head><body><header><div class="muted">POSY / PREVIEW · PRIVATE STAFF WORKSPACE</div><h1>Artwork review</h1><p>Read the complete brief. Inspect the exact image that would be released. Approval is a human decision, recorded against this image and this brief.</p></header>
<main><div class="bar"><label for="key">Reviewer key</label><input id="key" type="password" autocomplete="off" placeholder="Private reviewer credential"><button id="connect" class="primary">Open queue</button><button id="refresh" hidden>Refresh</button><button id="logout" hidden>Sign out</button></div>
<p class="muted">The key stays in this tab's memory. No automatic artwork approval or retry occurs here.</p><p id="status" role="status" aria-live="polite"></p>
<div class="layout" id="workspace" hidden><nav id="queue" aria-label="Artwork requests"></nav><article id="review" hidden>
<h2 id="title"></h2><p id="state"></p><h3>Complete saved brief</h3><pre id="brief"></pre><button id="generate" hidden>Generate one candidate (paid)</button>
<section id="candidate" hidden><h3>Exact delivery image</h3><p class="muted">Inspect the phone-sized view and full-size image. If an identity is unfamiliar, verify it against a trusted reference before approving. Do not guess.</p>
<div class="viewer"><img id="art" alt="Candidate artwork awaiting review"></div><button id="size">View full size</button><p class="muted" id="fingerprint"></p>
<fieldset id="checks"><legend>Required human checks</legend>
<label class="check"><input type="checkbox" value="fullBrief">Every requested subject, count, detail and exclusion matches the full brief.</label>
<label class="check"><input type="checkbox" value="identity">Named characters or references are accurate; unfamiliar identities have been independently verified.</label>
<label class="check"><input type="checkbox" value="medium">The requested artistic medium and style are visibly present.</label>
<label class="check"><input type="checkbox" value="finish">Composition, anatomy, edges and visible finish pass at phone and full size.</label>
<label class="check"><input type="checkbox" value="textFree">No unwanted lettering, logo or watermark appears.</label></fieldset>
<label for="note">Review note — include references checked and any defects</label><textarea id="note" maxlength="2000"></textarea><div class="bar"><button id="approve" class="primary" disabled>Approve and release this image</button><button id="reject" disabled>Reject this image</button></div></section>
<section id="correction" hidden><h3>Request a corrected candidate</h3><p>The rejected image and its review stay in the history. Describe what the next candidate must fix while preserving the complete saved brief.</p><label for="correction-note">Required corrections</label><textarea id="correction-note" maxlength="2000"></textarea><p class="muted" id="correction-limit"></p><button id="queue-correction" disabled>Queue correction — no charge</button><p class="muted">Queueing makes no image call. Staff must separately choose “Generate one candidate (paid)” when paid generation is enabled. A new image needs a new review.</p></section>
<section id="previous" hidden><h3>Previous rejected images</h3><p class="muted">Retained for comparison only. These images cannot be approved or released.</p><div class="bar" id="previous-list"></div><p class="muted" id="previous-label"></p><div class="viewer"><img id="previous-art" alt="Previous rejected artwork" hidden></div><button id="previous-size" hidden>View full size</button></section>
<h3>Decision history</h3><pre id="history"></pre></article></div></main>
<script>
(() => {
 const el=id=>document.getElementById(id); let key='', rows=[], selected=null, objectUrl=null, previousUrl=null, previousEpoch=0, loaded=false, fullSeen=false, generationEnabled=false, busy=false, epoch=0;
 const status=s=>el('status').textContent=s;
 const request=async(path, options={})=>{const r=await fetch('/api/staff/artwork-reviews'+path,{...options,cache:'no-store',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'}}); if(!r.ok){let data={};try{data=await r.json()}catch{}throw Error(data.error||'Request failed. Refresh and try again.')}return r};
 function resetImage(){if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=null;el('art').removeAttribute('src');el('art').classList.remove('full');el('size').textContent='View full size';loaded=false;fullSeen=false}
 function resetPrevious(){++previousEpoch;if(previousUrl)URL.revokeObjectURL(previousUrl);previousUrl=null;el('previous-art').removeAttribute('src');el('previous-art').hidden=true;el('previous-art').classList.remove('full');el('previous-size').hidden=true;el('previous-size').textContent='View full size';el('previous-label').textContent=''}
 const hashBytes=async blob=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');
 function controls(){const editable=selected&&selected.state==='review'&&!selected.stale&&loaded&&!busy;el('approve').disabled=!editable||!fullSeen||el('note').value.trim().length<5||[...el('checks').querySelectorAll('input')].some(i=>!i.checked);el('reject').disabled=!editable||el('note').value.trim().length<5;el('generate').disabled=busy;el('queue-correction').disabled=!(selected&&selected.state==='rejected'&&!selected.stale&&loaded&&!busy&&selected.correctionsRemaining>0&&el('correction-note').value.trim().length>=5);}
 async function openPrevious(row,previous){resetPrevious();const ticket=epoch,previousTicket=previousEpoch;try{const blob=await(await request('/'+encodeURIComponent(row.id)+'/previous/'+previous.version+'/asset')).blob();const hash=await hashBytes(blob);if(ticket!==epoch||previousTicket!==previousEpoch)return;if(hash!==previous.imageHash)throw Error('Retained image does not match its fingerprint.');previousUrl=URL.createObjectURL(blob);el('previous-art').src=previousUrl;el('previous-art').hidden=false;el('previous-size').hidden=false;el('previous-label').textContent='Rejected candidate at version '+previous.version+' · SHA-256: '+hash;}catch(e){if(ticket===epoch&&previousTicket===previousEpoch)status(e.message)}}
 async function open(row){const ticket=++epoch; selected=row;resetImage();resetPrevious();el('note').value='';el('correction-note').value='';el('checks').querySelectorAll('input').forEach(i=>i.checked=false);el('review').hidden=false;el('title').textContent='Event '+row.eventId+' · '+row.brief.eventName;el('state').textContent=row.state+(row.stale?' — brief changed; cannot release':'');el('brief').textContent=JSON.stringify(row.brief,null,2);el('history').textContent=JSON.stringify(row.history,null,2);el('candidate').hidden=!row.imageHash;el('generate').hidden=!(generationEnabled&&row.state==='queued'&&!row.stale);el('fingerprint').textContent='Image SHA-256: '+(row.imageHash||'');el('correction').hidden=row.state!=='rejected';el('correction-limit').textContent=row.correctionsRemaining>0?row.correctionsRemaining+' correction request(s) remain for this brief in Preview.':'The Preview correction limit has been reached. Staff must resolve this request before proceeding.';el('previous').hidden=!(row.previousCandidates||[]).length;el('previous-list').replaceChildren();for(const previous of row.previousCandidates||[]){const b=document.createElement('button');b.textContent='View rejected candidate · version '+previous.version;b.onclick=()=>openPrevious(row,previous);el('previous-list').append(b)}controls();
  if(row.imageHash){try{const r=await request('/'+encodeURIComponent(row.id)+'/asset');const blob=await r.blob();if(ticket!==epoch)return;const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');if(ticket!==epoch)return;if(hash!==row.imageHash)throw Error('Image changed. Reload before reviewing.');objectUrl=URL.createObjectURL(blob);el('art').onload=()=>{if(ticket===epoch){loaded=true;controls()}};el('art').src=objectUrl}catch(e){if(ticket===epoch)status(e.message)}}
 }
 async function refresh(){const ticket=epoch, requestKey=key;const data=await(await request('')).json();if(ticket!==epoch||requestKey!==key)return;rows=data.reviews;generationEnabled=data.generationEnabled;el('workspace').hidden=false;el('refresh').hidden=false;el('logout').hidden=false;el('queue').replaceChildren();for(const row of rows){const b=document.createElement('button');b.textContent='Event '+row.eventId+' · '+row.state+(row.stale?' · changed':'');b.onclick=()=>open(row);el('queue').append(b)}status(rows.length?rows.length+' retained request(s).':'No requests in this Preview queue.');const row=selected&&rows.find(r=>r.id===selected.id);if(row)await open(row);else{selected=null;resetImage();resetPrevious();el('review').hidden=true}}
 el('connect').onclick=async()=>{key=el('key').value;el('key').value='';try{await refresh()}catch(e){key='';status(e.message)}};
 el('refresh').onclick=()=>refresh().catch(e=>status(e.message));
 el('logout').onclick=()=>{++epoch;key='';rows=[];selected=null;resetImage();resetPrevious();el('workspace').hidden=true;el('refresh').hidden=true;el('logout').hidden=true;el('queue').replaceChildren();el('previous-list').replaceChildren();for(const id of ['brief','history','title','state','fingerprint'])el(id).textContent='';el('note').value='';el('correction-note').value='';el('checks').querySelectorAll('input').forEach(i=>i.checked=false);status('Signed out.')};
 el('size').onclick=()=>{el('art').classList.toggle('full');if(el('art').classList.contains('full'))fullSeen=true;el('size').textContent=el('art').classList.contains('full')?'View phone size':'View full size';controls()};
 el('previous-size').onclick=()=>{el('previous-art').classList.toggle('full');el('previous-size').textContent=el('previous-art').classList.contains('full')?'View phone size':'View full size'};
 el('checks').onchange=controls;el('note').oninput=controls;el('correction-note').oninput=controls;
 el('queue-correction').onclick=async()=>{if(!selected||busy||el('queue-correction').disabled)return;busy=true;controls();try{await request('/'+encodeURIComponent(selected.id)+'/correction',{method:'POST',body:JSON.stringify({version:selected.version,imageHash:selected.imageHash,briefHash:selected.briefHash,note:el('correction-note').value.trim()})});await refresh();status('Correction queued. No image was generated and no charge was made. A new candidate needs a fresh review.')}catch(e){status(e.message)}finally{busy=false;controls()}};
 async function decide(decision){if(!selected||busy)return;busy=true;controls();try{await request('/'+encodeURIComponent(selected.id)+'/decision',{method:'POST',body:JSON.stringify({decision,version:selected.version,imageHash:selected.imageHash,briefHash:selected.briefHash,checks:[...el('checks').querySelectorAll('input:checked')].map(i=>i.value),note:el('note').value.trim()})});await refresh();status(decision==='approved'?'Approved. Only this image and brief can be released.':'Rejected. No automatic regeneration will run.')}catch(e){status(e.message)}finally{busy=false;controls()}}
 el('approve').onclick=()=>decide('approved');el('reject').onclick=()=>decide('rejected');
 el('generate').onclick=async()=>{if(!selected||busy||!confirm('Generate one paid image for this complete brief? No retry will run.'))return;busy=true;controls();try{await request('/'+encodeURIComponent(selected.id)+'/generate',{method:'POST',body:JSON.stringify({confirmOneImage:true,version:selected.version,briefHash:selected.briefHash})});await refresh();status('One generation scheduled. Refresh to inspect its retained result.')}catch(e){status(e.message)}finally{busy=false;controls()}};
})();
</script></body></html>`;
